#!/bin/bash
echo ""
clear
echo ""
echo -e ""
echo ""
echo ""
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------  \e[1;91m\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;33m\e[0m\e[1;90m\e[0m\e[1;92m  !!       Welcome to Cybersnipper     !!\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ---------------------------------------- \e[1;91m\e[0m'
echo ""
echo -e ""
echo -e " \e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m \e[95m To Install and use this tool, you must join our whatsapp channel \e[0m"
echo ""
echo -e " \e[91m[\e[92m*\e[91m]\e[1;93m Channel Link :\e[0m\e[1;36m https://whatsapp.com/channel/0029VaN8F9MG8l5KA9Jx0Q0X  "
echo ""
echo ""
echo ""
read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Have you joined channel ? \e[1;91m (Y/N) : \e[0m' option
echo""
echo""
echo""
if [[ $option == *'N'* ]]; then
clear
exit
fi
if [[ $option == *'n'* ]]; then
clear
exit
fi
clear
echo ""
echo -e " \e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m Checking if ure a member Please Wait....  \e[0m"
echo -e ""
clear
echo ""
echo ""
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------  \e[1;91m\e[0m'
echo -e $'\e[1;96m\e[0m\e[1;77m\e[0m\e[1;96m\e[0m\e[1;91m  !!      CHECKING IF YOU JOINED CHANNEL    !!\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------- \e[1;91m\e[0m'
echo ""
xdg-open "https://whatsapp.com/channel/0029VaN8F9MG8l5KA9Jx0Q0X"
sleep 10
echo ""
echo -e "\e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m Installing The Facebook Hacking Tool Please Wait....  \e[0m"
echo ""
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------  \e[1;91m\e[0m'
echo -e $'\e[1;96m\e[0m\e[1;77m\e[0m\e[1;96m\e[0m\e[1;91m  !!          DOWNLOADING CRACKERS         !!\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------- \e[1;91m\e[0m'
echo ""
echo -e "\e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m \e[95m Resonex Cruze \e[0m"
echo ""
sleep 2
termux-setup-storage
apt-get update -y
apt-get upgrade -y
apt install php -y
apt install git -y
apt install wget -y
apt install curl -y
apt install unzip -y
clear
echo '
      ---------------------------------   
    !!    Installation Successfull     !!  
      ---------------------------------   ' | lolcat
sleep 2
clear
echo
echo -e "\e[1m \e[36m[+] This is The Last Step if you need password of the tool, visit our channel\e[m \e[21"
echo
echo -e "\e[1m \e[36m[+] Channel: https://whatsapp.com/channel/0029VaN8F9MG8l5KA9Jx0Q0X \e[m \e[21"
echo
echo -e "\e[92m[+] Now type this command:\e[93m python2 spam.py \e[m "
echo
